# Generated by Django 5.1.2 on 2024-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_school', '0002_enrollment_expiry_date_enrollment_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
