# Generated by Django 5.1.2 on 2024-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_school', '0003_lesson_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
