# Generated by Django 5.1.2 on 2024-10-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_school', '0004_alter_discountcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
